name: Build PyQt Executable

on:
  push:
    branches:
      - main  # Adjust if you want to target different branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the latest code from the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./client/requirements.txt
          pip install pyinstaller

      # Build the PyQt executable
      - name: Build executable
        run: |
          pyinstaller --onefile ./client/src/main.py

      # Upload the executable as an artifact
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: pyqt-executable
          path: dist/main
